CREATE TABLE IF NOT EXISTS books (
    b_id INT AUTO_INCREMENT PRIMARY KEY,
    b_name VARCHAR(100) NOT NULL,
    b_desc VARCHAR(300) NOT NULL,
    b_img VARCHAR(100) NOT NULL,
    b_year VARCHAR(10) NOT NULL
);