INSERT IGNORE INTO authors (a_id, a_name)
VALUES (1, 'Андрей Богуславский'),
       (2, 'Марк Саммерфильд'),
       (3, 'М., Вильямс'),
       (4, 'Уэс Маккинни'),
       (5, 'Брюс Эккель'),
       (6, 'Томас Кормен, Чарльз Лейзерсон, Рональд Ривест, Клиффорд Штайн'),
       (7,'Дэвид Флэнаган'),
       (8,'Гэри Маклин Холл'),
       (9, 'Джеймс Р. Грофф'),
       (10, 'Люк Веллинг'),
       (11, 'Сергей Мастицкий'),
       (12, 'Джон Вудкок'),
       (13, 'Джереми Блум'),
       (14,'А. Белов'),
       (15, 'Сэмюэл Грингард'),
       (16, 'Сет Гринберг'),
       (17, 'Александр Сераков'),
       (18, 'Тим Кедлек'),
       (19, 'Пол Дейтел, Харви Дейтел'),
       (20, 'Роберт Мартин'),
       (21, 'Энтони Грей'),
       (22, 'Мартин Фаулер, Прамодкумар Дж. Садаладж'),
       (23, 'Джей Макгаврен'),
       (24, 'Дрю Нейл');

INSERT IGNORE INTO books (b_id, b_name, b_desc, b_img, b_year)
VALUES (1, 'СИ++ И КОМПЬЮТЕРНАЯ ГРАФИКА', 'Книга про СИ++ И КОМПЬЮТЕРНАЯ ГРАФИКА', '22.jpg', '2024-01-01'),
       (2, 'Программирование на языке Go!', 'Книга про Программирование на языке Go!', '23.jpg', '2024-01-01'),
       (3, 'Толковый словарь сетевых терминов и аббревиатур', 'Книга про Толковый словарь сетевых терминов и аббревиатур',
        '25.jpg', '2024-01-01'),
       (4, 'Python for Data Analysis', 'Книга про Python for Data Analysis', '26.jpg', '2024-01-01'),
       (5, 'Thinking in Java (4th Edition)', 'Книга про Thinking in Java (4th Edition)', '27.jpg', '2024-01-01'),
       (6, 'Introduction to Algorithms', 'Книга про Introduction to Algorithms', '29.jpg', '2024-01-01'),
       (7, 'JavaScript Pocket Reference', 'Книга про JavaScript Pocket Reference', '31.jpg', '2024-01-01'),
       (8, 'Adaptive Code via C#: Class and Interface Design, Design Patterns, and SOLID Principles',
        'Книга про Adaptive Code via C#', '32.jpg', '2024-01-01'),
       (9, 'SQL: The Complete Reference', 'Книга про SQL: The Complete Reference', '33.jpg', '2024-01-01'),
       (10, 'PHP and MySQL Web Development', 'Книга про PHP and MySQL Web Development', '34.jpg', '2024-01-01'),
       (11, 'Статистический анализ и визуализация данных с помощью R',
        'Книга про Статистический анализ и визуализация данных с помощью R', '35.jpg', '2024-01-01'),
       (12, 'Computer Coding for Kids', 'Книга про Computer Coding for Kids', '36.jpg', '2024-01-01'),
       (13, 'Exploring Arduino: Tools and Techniques for Engineering Wizardry', 'Книга про Exploring Arduino', '37.jpg',
        '2024-01-01'),
       (14, 'Программирование микроконтроллеров для начинающих и не только', 'Книга про Программирование микроконтроллеров',
        '38.jpg', '2024-01-01'),
       (15, 'The Internet of Things', 'Книга про The Internet of Things', '39.jpg', '2024-01-01'),
       (16, 'Sketching User Experiences: The Workbook', 'Книга про Sketching User Experiences', '40.jpg', '2024-01-01'),
       (17, 'InDesign CS6', 'Книга про InDesign CS6', '41.jpg', '2024-01-01'),
       (18, 'Адаптивный дизайн. Делаем сайты для любых устройств', 'Книга про Адаптивный дизайн', '42.jpg', '2024-01-01'),
       (19, 'Android для разработчиков', 'Книга про Android для разработчиков', '43.jpg', '2024-01-01'),
       (20, 'Clean Code: A Handbook of Agile Software Craftsmanship', 'Книга про Clean Code', '44.jpg', '2024-01-01'),
       (21, 'Swift Pocket Reference: Programming for iOS and OS X', 'Книга про Swift Pocket Reference', '45.jpg',
        '2024-01-01'),
       (22, 'NoSQL Distilled: A Brief Guide to the Emerging World of Polyglot Persistence', 'Книга про NoSQL Distilled',
        '46.jpg', '2024-01-01'),
       (23, 'Head First Ruby', 'Книга про Head First Ruby', '47.jpg', '2024-01-01'),
       (24, 'Practical Vim', 'Книга про Practical Vim', '48.jpg', '2024-01-01');

INSERT IGNORE INTO authorBook (a_id, b_id)
VALUES (1, 1),
       (2, 2),
       (3, 3),
       (4, 4),
       (5, 5),
       (6, 6),
       (7, 7),
       (8, 8),
       (9, 9),
       (10, 10),
       (11, 11),
       (12, 12),
       (13, 13),
       (14, 14),
       (15, 15),
       (16, 16),
       (17, 17),
       (18, 18),
       (19, 19),
       (20, 20),
       (21, 21),
       (22, 22),
       (23, 23),
       (24, 24);